---
# tasks file for sbaerlocher.proxmox

- name: 'proxmox : generate DHE key-exchange'
  become: true
  command: openssl dhparam -dsaparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    chdir: /etc/ssl/certs
    creates: dhparam.pem

- name: 'proxmox : configuration pveproxy'
  become: true
  template:
    src: 'etc/default/pveproxy.j2'
    dest: '/etc/default/pveproxy'
    owner: root
    group: www-data
    mode: '0440'
  notify:
    - restart pveproxy
