---
# tasks file for sbaerlocher.proxmox

- name: 'proxmox : generate DHE key-exchange'
  become: true
  command: openssl dhparam -dsaparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    chdir: /etc/ssl/certs
    creates: dhparam.pem

- name: 'proxmox : configuration pveproxy'
  become: true
  template:
    src: 'etc/default/pveproxy.j2'
    dest: '/etc/default/pveproxy'
    owner: root
    group: www-data
    mode: '0440'
  notify:
    - restart pveproxy

- name: 'proxmox : download iso'
  get_url:
    url: '{{ item.url }}'
    dest: '/var/lib/vz/template/iso/{{ item.name }}.iso'
    mode: 0440
  when: item.state != 'absent'
  with_items:
    - '{{ proxmox_pve_iso }}'

- name: 'proxmox : delete iso'
  file:
    dest: '/var/lib/vz/template/iso/{{ item.name }}.iso'
    state: absent
  when: item.state == 'absent'
  with_items:
    - '{{ proxmox_pve_iso }}'
